apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: argo-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          ports:
            - containerPort: 10000  # Blob service
            - containerPort: 10001  # Queue service
            - containerPort: 10002  # Table service
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: argo-events
spec:
  selector:
    app: azurite
  ports:
    - protocol: TCP
      name: blob
      port: 10000
      targetPort: 10000
    - protocol: TCP
      name: queue
      port: 10001
      targetPort: 10001
    - protocol: TCP
      name: table
      port: 10002
      targetPort: 10002