apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: azure-blob-storage-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: azure-blob-storage
      eventSourceName: azure-blob-storage
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: azure-blob-workflow-
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:3.7
                      command: [sh, -c]
                      args: ["echo Hello from Argo Workflow triggered by Azure Blob Storage!"]